---
options:
  - name: mongodb-version
    value: 5.0.0
  - name: mongodb-replica-set
    value:
  - name: mongodb-port
    value:
  - name: mongodb-db
    value:
  - name: mongodb-username
    value:
  - name: mongodb-password
    value:
