# frozen_string_literal: true

RSpec.describe(GHB::AutoMergeManager) do
  let(:auto_merge_workflow) { GHB::Workflow.new('Auto-approve for code owners') }

  before do
    allow($stdout).to(receive(:puts))
    allow(FileUtils).to(receive(:mkdir_p))
    allow(FileUtils).to(receive(:rm_f))
    allow(File).to(receive(:write))
  end

  describe '#save' do
    it 'generates the auto-approve workflow file' do
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(File).to(have_received(:write).with('.github/workflows/auto-approve.yml', anything))
    end

    it 'removes the legacy auto-merge workflow file' do
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(FileUtils).to(have_received(:rm_f).with('.github/workflows/auto-merge.yml'))
    end

    it 'sets the correct trigger' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(auto_merge_workflow.on).to(
        eq(
          {
            pull_request_target:
              {
                types: %w[opened reopened ready_for_review synchronize]
              }
          }
        )
      )
    end

    it 'sets least-privilege permissions (contents: read only)' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(auto_merge_workflow.permissions).to(
        eq(
          {
            contents: 'read'
          }
        )
      )
    end

    it 'creates the auto_approve job' do # rubocop:disable RSpec/MultipleExpectations
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(auto_merge_workflow.jobs).to(have_key(:auto_approve))
      expect(auto_merge_workflow.jobs[:auto_approve].name).to(eq('Auto-approve'))
    end

    it 'skips drafts and blocks fork pull requests' do
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(auto_merge_workflow.jobs[:auto_approve].if).to(
        eq('github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.repository')
      )
    end

    it 'sets a per-PR concurrency group' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(auto_merge_workflow.concurrency).to(
        eq(
          {
            group: 'auto-approve-${{github.event.pull_request.number}}',
            'cancel-in-progress': true
          }
        )
      )
    end

    it 'writes an auto-generated header into the workflow file' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      expect(File).to(
        have_received(:write).with(
          '.github/workflows/auto-approve.yml',
          a_string_starting_with('# AUTO-GENERATED by github-build')
        )
      )
    end

    it 'includes a checkout step with base sha' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      checkout_step = auto_merge_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Checkout' }
      expect(checkout_step).not_to(be_nil)
      expect(checkout_step.uses).to(eq('actions/checkout@v6'))
      expect(checkout_step.with[:ref]).to(eq('${{github.event.pull_request.base.sha}}'))
    end

    it 'includes a code owner check step' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      check_step = auto_merge_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Check if PR author is a code owner' }
      expect(check_step).not_to(be_nil)
      expect(check_step.id).to(eq('check'))
      expect(check_step.run).to(include('CODEOWNERS'))
      expect(check_step.run).to(include('is_owner'))
      expect(check_step.env[:GH_TOKEN]).to(eq('${{secrets.GH_PAT}}'))
    end

    it 'includes an approve PR step' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      approve_step = auto_merge_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Approve PR' }
      expect(approve_step).not_to(be_nil)
      expect(approve_step.if).to(eq("steps.check.outputs.is_owner == 'true'"))
      expect(approve_step.run).to(eq('gh pr review --approve "$PR"'))
      expect(approve_step.env[:GH_TOKEN]).to(eq('${{secrets.GH_BOT_PAT}}'))
    end

    it 'does not include a merge step' do
      manager = described_class.new(auto_merge_workflow: auto_merge_workflow)
      manager.save

      merge_step = auto_merge_workflow.jobs[:auto_approve].steps.find { |s| s.name&.match?(/merge/i) }
      expect(merge_step).to(be_nil)
    end
  end
end
