# frozen_string_literal: true

require 'open3'

RSpec.describe(GHB::AutoApproveManager) do
  let(:auto_approve_workflow) { GHB::Workflow.new('Auto-approve for code owners') }

  before do
    allow($stdout).to(receive(:puts))
    allow(FileUtils).to(receive(:mkdir_p))
    allow(FileUtils).to(receive(:rm_f))
    allow(File).to(receive(:write))
  end

  describe '#save' do
    it 'generates the auto-approve workflow file' do
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(File).to(have_received(:write).with('.github/workflows/auto-approve.yml', anything))
    end

    it 'removes the legacy auto-merge workflow file' do
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(FileUtils).to(have_received(:rm_f).with('.github/workflows/auto-merge.yml'))
    end

    it 'sets the correct trigger' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(auto_approve_workflow.on).to(
        eq(
          {
            pull_request_target:
              {
                types: %w[opened reopened ready_for_review synchronize]
              }
          }
        )
      )
    end

    it 'sets least-privilege permissions (contents: read only)' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(auto_approve_workflow.permissions).to(
        eq(
          {
            contents: 'read'
          }
        )
      )
    end

    it 'creates the auto_approve job' do # rubocop:disable RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(auto_approve_workflow.jobs).to(have_key(:auto_approve))
      expect(auto_approve_workflow.jobs[:auto_approve].name).to(eq('Auto-approve'))
    end

    it 'skips drafts and blocks fork pull requests' do
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(auto_approve_workflow.jobs[:auto_approve].if).to(
        eq('github.event.pull_request.draft == false && github.event.pull_request.head.repo.full_name == github.repository')
      )
    end

    it 'sets a per-PR concurrency group' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(auto_approve_workflow.concurrency).to(
        eq(
          {
            group: 'auto-approve-${{github.event.pull_request.number}}',
            'cancel-in-progress': true
          }
        )
      )
    end

    it 'writes an auto-generated header into the workflow file' do # rubocop:disable RSpec/ExampleLength
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      expect(File).to(
        have_received(:write).with(
          '.github/workflows/auto-approve.yml',
          a_string_starting_with('# AUTO-GENERATED by github-build')
        )
      )
    end

    it 'includes a checkout step with base sha' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      checkout_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Checkout' }
      expect(checkout_step).not_to(be_nil)
      expect(checkout_step.uses).to(eq(GHB.external_action('actions/checkout')))
      expect(checkout_step.with[:ref]).to(eq('${{github.event.pull_request.base.sha}}'))
    end

    it 'includes a code owner check step' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      check_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Check if PR author is a code owner' }
      expect(check_step).not_to(be_nil)
      expect(check_step.id).to(eq('check'))
      expect(check_step.run).to(include('CODEOWNERS'))
      expect(check_step.run).to(include('is_owner'))
      expect(check_step.env[:GH_TOKEN]).to(eq('${{secrets.GH_BOT_PAT}}'))
    end

    it 'exposes only GH_TOKEN and AUTHOR to the code owner check step (no dead ORG var)' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      check_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Check if PR author is a code owner' }
      expect(check_step.env).to(
        eq(
          {
            GH_TOKEN: '${{secrets.GH_BOT_PAT}}',
            AUTHOR: '${{github.event.pull_request.user.login}}'
          }
        )
      )
      expect(check_step.env).not_to(have_key(:ORG))
      expect(check_step.run).not_to(include('$ORG'))
    end

    it 'includes an approve PR step' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      approve_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Approve PR' }
      expect(approve_step).not_to(be_nil)
      expect(approve_step.if).to(eq("steps.check.outputs.is_owner == 'true'"))
      expect(approve_step.run).to(include('gh pr review --approve "$PR"'))
      expect(approve_step.env[:GH_TOKEN]).to(eq('${{secrets.GH_BOT_PAT}}'))
      expect(approve_step.env[:AUTHOR]).to(eq('${{github.event.pull_request.user.login}}'))
    end

    it 'skips self-approval when the approver is the PR author' do # rubocop:disable RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      approve_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Approve PR' }
      expect(approve_step.run).to(include('APPROVER=$(gh api user --jq .login)'))
      expect(approve_step.run).to(include('skipping self-approval'))
    end

    context 'with the approve step' do
      subject(:approve_step) do
        described_class.new(auto_approve_workflow: auto_approve_workflow).save
        auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Approve PR' }
      end

      it 'passes the repository through env' do
        expect(approve_step.env[:REPO]).to(eq('${{github.repository}}'))
      end

      it 'passes the PR head sha through env' do
        expect(approve_step.env[:HEAD_SHA]).to(eq('${{github.event.pull_request.head.sha}}'))
      end

      it 'passes the run token through env' do
        expect(approve_step.env[:GITHUB_TOKEN]).to(eq('${{github.token}}'))
      end

      it 'reads the head commit with the run token, not GH_BOT_PAT' do
        expect(approve_step.run).to(include('SUBJECT=$(GH_TOKEN="$GITHUB_TOKEN" gh api "repos/${REPO}/commits/${HEAD_SHA}"'))
      end

      it 'does not interpolate workflow expressions into the script' do
        expect(approve_step.run).not_to(include('${{'))
      end
    end

    it 'does not include a merge step' do
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save

      merge_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name&.match?(/merge/i) }
      expect(merge_step).to(be_nil)
    end
  end

  # Runs the actual generated "Check if PR author is a code owner" bash script against a
  # sandbox CODEOWNERS file and returns [exit_status, github_output_contents, combined_stdout].
  # The sandbox is set up via bash (not stubbed Ruby File methods) so the global File.write /
  # FileUtils stubs above do not interfere.
  describe 'generated CODEOWNERS check script (BUG-001)' do
    def run_check_script(codeowners:, author:)
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save
      check_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Check if PR author is a code owner' }
      script = check_step.run

      Dir.mktmpdir do |dir|
        output_path = File.join(dir, 'github_output')
        prologue = <<~SH
          mkdir -p '#{dir}/.github'
          cat > '#{dir}/.github/CODEOWNERS' <<'CODEOWNERS_EOF'
          #{codeowners}
          CODEOWNERS_EOF
          export GITHUB_OUTPUT='#{output_path}'
          export AUTHOR='#{author}'
          cd '#{dir}'
        SH
        stdout_str, status = Open3.capture2e('bash', '-c', "#{prologue}\n#{script}")
        [status.exitstatus, File.exist?(output_path) ? File.read(output_path) : '', stdout_str]
      end
    end

    it 'degrades to is_owner=false (exit 0) when CODEOWNERS has no catch-all * line' do # rubocop:disable RSpec/MultipleExpectations
      exit_status, output, = run_check_script(codeowners: "docs/ @someone\n", author: 'alice')

      expect(exit_status).to(eq(0))
      expect(output).to(include('is_owner=false'))
    end

    it 'sets is_owner=true when the * line lists the PR author as an individual owner' do # rubocop:disable RSpec/MultipleExpectations
      exit_status, output, = run_check_script(codeowners: "* @alice @bob\n", author: 'alice')

      expect(exit_status).to(eq(0))
      expect(output).to(include('is_owner=true'))
    end

    it 'sets is_owner=false when the * line does not list the PR author' do # rubocop:disable RSpec/MultipleExpectations
      exit_status, output, = run_check_script(codeowners: "* @bob @carol\n", author: 'alice')

      expect(exit_status).to(eq(0))
      expect(output).to(include('is_owner=false'))
    end

    it 'degrades to is_owner=false (exit 0) when CODEOWNERS is empty' do # rubocop:disable RSpec/MultipleExpectations
      exit_status, output, = run_check_script(codeowners: "\n", author: 'alice')

      expect(exit_status).to(eq(0))
      expect(output).to(include('is_owner=false'))
    end

    it 'still emits is_owner=false (exit 0) when no CODEOWNERS file exists' do # rubocop:disable RSpec/ExampleLength,RSpec/MultipleExpectations
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save
      check_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Check if PR author is a code owner' }
      script = check_step.run

      exit_status, output =
        Dir.mktmpdir do |dir|
          output_path = File.join(dir, 'github_output')
          prologue = "export GITHUB_OUTPUT='#{output_path}'\nexport AUTHOR='alice'\ncd '#{dir}'\n"
          _stdout_str, status = Open3.capture2e('bash', '-c', "#{prologue}#{script}")
          [status.exitstatus, File.exist?(output_path) ? File.read(output_path) : '']
        end

      expect(exit_status).to(eq(0))
      expect(output).to(include('is_owner=false'))
    end
  end

  describe 'generated approve script' do
    def run_approve_script(commit_message:, commit_lookup_fails: false)
      manager = described_class.new(auto_approve_workflow: auto_approve_workflow)
      manager.save
      approve_step = auto_approve_workflow.jobs[:auto_approve].steps.find { |s| s.name == 'Approve PR' }
      script = approve_step.run

      Dir.mktmpdir do |dir|
        gh_stub = <<~SH
          mkdir -p '#{dir}/bin'
          cat > '#{dir}/bin/gh' <<'GH_EOF'
          #!/usr/bin/env bash
          case "$1 $2" in
            "api user") [ "$GH_TOKEN" = bot-pat ] || exit 3; echo approver-bot ;;
            "api repos/"*) [ "$GH_TOKEN" = run-token ] || exit 3; [ -n "${COMMIT_LOOKUP_FAILS}" ] && exit 1; printf '%s' "$COMMIT_MESSAGE_FIXTURE" ;;
            "pr review") [ "$GH_TOKEN" = bot-pat ] || exit 3; echo "APPROVED PR $4" ;;
            *) exit 2 ;;
          esac
          GH_EOF
          chmod +x '#{dir}/bin/gh'
          export PATH='#{dir}/bin':"$PATH"
        SH
        env = {
          GH_TOKEN: 'bot-pat',
          GITHUB_TOKEN: 'run-token',
          AUTHOR: 'alice',
          PR: '42',
          REPO: 'org/repo',
          HEAD_SHA: 'abc123',
          COMMIT_MESSAGE_FIXTURE: commit_message,
          COMMIT_LOOKUP_FAILS: commit_lookup_fails ? '1' : ''
        }.transform_keys(&:to_s)
        stdout_str, status = Open3.capture2e(env, 'bash', '-c', "#{gh_stub}\n#{script}")
        [status.exitstatus, stdout_str]
      end
    end

    it 'approves when the head commit subject has no skip trigger' do
      expect(run_approve_script(commit_message: 'Add feature')).to(eq([0, "APPROVED PR 42\n"]))
    end

    %w[#skip-all #skip-tests #skip-linters #skip-licenses #SKIP-ALL].each do |trigger|
      it "withholds approval when the head commit subject contains #{trigger}" do
        expect(run_approve_script(commit_message: "Quick fix #{trigger}")).to(
          eq([0, "Head commit uses #{trigger.downcase}, so required checks may be skipped; human review is required.\n"])
        )
      end
    end

    it 'ignores skip triggers outside the first line of the commit message' do
      expect(run_approve_script(commit_message: "Add feature\n\nMentions #skip-all in the body")).to(eq([0, "APPROVED PR 42\n"]))
    end

    it 'fails without approving when the head commit cannot be read' do
      expect(run_approve_script(commit_message: 'Add feature', commit_lookup_fails: true)).to(eq([1, '']))
    end
  end
end
