---
# Lint directives.
lint:
  rules:
    all_default: true

    remove:
      - ENUMS_HAVE_COMMENT
      - ENUM_FIELDS_HAVE_COMMENT
      - ENUM_FIELD_NAMES_PREFIX
      - ENUM_FIELD_NAMES_UPPER_SNAKE_CASE
      - ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH
      - FIELDS_HAVE_COMMENT
      - FIELD_NAMES_EXCLUDE_PREPOSITIONS
      - FIELD_NAMES_LOWER_SNAKE_CASE
      - FILE_HAS_COMMENT
      - INDENT
      - MAX_LINE_LENGTH
      - MESSAGES_HAVE_COMMENT
      - REPEATED_FIELD_NAMES_PLURALIZED
      - RPCS_HAVE_COMMENT
      - RPC_NAMES_CASE
      - SERVICES_HAVE_COMMENT
      - SERVICE_NAMES_END_WITH
      - SERVICE_NAMES_UPPER_CAMEL_CASE
      - SYNTAX_CONSISTENT
