---
name: Cron Dependencies
'on':
  schedule:
  - cron: "*/10 * * * *"
env:
  RUBY-BUNDLER-CACHE: true
  RUBY-VERSION: 3.4.1
jobs:
  update_dependencies:
    name: Update Dependencies
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: cloud-officer/ci-actions/setup@master
      with:
        ssh-key: "${{secrets.SSH_KEY}}"
        aws-access-key-id: "${{secrets.AWS_ACCESS_KEY_ID}}"
        aws-secret-access-key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
        aws-region: "${{secrets.AWS_DEFAULT_REGION}}"
        ruby-version: "${{env.RUBY-VERSION}}"
        ruby-bundler-cache: "${{env.RUBY-BUNDLER-CACHE}}"
    - name: Update Dependencies
      shell: bash
      run: |
        if [ -f "composer.lock" ]; then
          composer update
        fi

        if [ -f "Gemfile.lock" ]; then
          bundle config set frozen false
          bundle update
        fi

        if [ -f "requirements.txt" ]; then
          pip-compile --resolver=backtracking --upgrade
        fi
    - name: Get SOUP Code
      shell: bash
      id: soup
      run: |
        latest_tag="$(curl --silent --header "Authorization: Bearer ${{ inputs.github-token }}" https://api.github.com/repos/Cloud-Officer/soup/tags | jq -r '.[0].name')"
        echo "Latest soup tag: ${latest_tag}"
        asset_url=""https://github.com/Cloud-Officer/soup/archive/refs/tags/${latest_tag}.zip""
        curl -L "${asset_url}" -o "${RUNNER_TEMP}/soup.zip"
        unzip -q "${RUNNER_TEMP}/soup.zip" -d "${RUNNER_TEMP}"
        rm -rf "${RUNNER_TEMP}/soup.zip"
        echo "soup_location=${RUNNER_TEMP}/soup-${latest_tag}" >> ${GITHUB_ENV}
    - name: Run SOUP
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        pushd "${{env.soup_location}}"
        bundle config unset deployment
        bundle install
        popd
        "${{env.soup_location}}/bin/soup.rb" ${{ inputs.parameters }}
    - name: Set GitHub to use https with credentials
      id: check_changes
      shell: bash
      run: |
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com:
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf https://github.com/
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf git@github.com:
        git add .
        git status

        if git diff --cached --exit-code; then
          echo "changes=false" >> $GITHUB_OUTPUT
        else
          echo "changes=true" >> $GITHUB_OUTPUT
        fi
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update dependencies and soup files
        branch: update-dependencies-${{github.run_id}}
        title: Update Dependencies
        body: This PR updates the dependencies.
