---
name: Cron Dependencies
'on':
  schedule:
  - cron: 0 9 * * 1
env:
  RUBY-BUNDLER-CACHE: true
  RUBY-VERSION: 3.4.7
jobs:
  update_dependencies:
    name: Update Dependencies
    permissions:
      actions: write
      checks: write
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Setup
      uses: cloud-officer/ci-actions/setup@master
      with:
        ssh-key: "${{secrets.SSH_KEY}}"
        aws-access-key-id: "${{secrets.AWS_ACCESS_KEY_ID}}"
        aws-secret-access-key: "${{secrets.AWS_SECRET_ACCESS_KEY}}"
        aws-region: "${{secrets.AWS_DEFAULT_REGION}}"
        ruby-version: "${{env.RUBY-VERSION}}"
        ruby-bundler-cache: "${{env.RUBY-BUNDLER-CACHE}}"
    - name: Update Dependencies
      shell: bash
      run: |
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf ssh://git@github.com:
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf https://github.com/
        git config --global --add url."https://${{secrets.SOUP_DEPENDENCIES_UPDATE}}:x-oauth-basic@github.com/".insteadOf git@github.com:

        bundle config set frozen false ; bundle update
    - name: Licenses
      uses: cloud-officer/ci-actions/soup@master
      with:
        ssh-key: "${{secrets.SSH_KEY}}"
        github-token: "${{secrets.SOUP_DEPENDENCIES_UPDATE}}"
        parameters: "--no_prompt --soup"
        skip-checkout: 'true'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        commit-message: Update dependencies and soup files
        branch: update-dependencies-${{github.run_id}}
        title: Update Dependencies
        body: This PR updates the dependencies.
        token: "${{secrets.SOUP_DEPENDENCIES_UPDATE}}"
